import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Sidebar from '@/component/AdminComponent/sidebar';
import AdminHeader from '@/component/AdminComponent/AdminHeader';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`flex ${montserrat.className} bg-white`}>
      <div className="hidden lg:block">
        <Sidebar />
      </div>
      <div className="flex flex-col w-full">
        <AdminHeader />
        {children}
      </div>
    </div>
  );
}
